apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: adguard
  namespace: adguard
spec:
  ports:
  - name: 443-443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: adguard
  type: ClusterIP