apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik

spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`authentik.lisa`)

    observability:
      accessLogs: true
      metrics: true
      tracing: true

    services:
      - name: authentik-server
        port: 80