apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireProbe
metadata:
  name: pods-must-have-probe-check
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
