apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: authentik-vault-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik
        property: secret_key 

    - secretKey: postgresql_password
      remoteRef:
        key: authentik
        property: postgresql_password