apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: renovate-vault-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: rennovate
        property: GITHUB_PAT
