authentik:
  secret_key: file:///vault-secrets/secret_key
  postgresql:
    password: file:///vault-secrets/postgresql_password

server:
  volumes:
    - name: vault-secrets
      secret:
        secretName: authentik-vault-secrets
  volumeMounts:
    - name: vault-secrets
      mountPath: /vault-secrets
      readOnly: true

worker:
  volumes:
    - name: vault-secrets
      secret:
        secretName: authentik-vault-secrets
  volumeMounts:
    - name: vault-secrets
      mountPath: /vault-secrets
      readOnly: true