apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-oidc-secret
    creationPolicy: Owner
  data:
  - secretKey: oidc_secret
    remoteRef:
      key: grafana
      property: oidc_secret

  - secretKey: ca_root
    remoteRef:
      key: grafana
      property: ca_root