apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: grafana
spec:
  provider:
    vault:
      server: "https://vault.lisa"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: "grafana-role"
          serviceAccountRef:
            name: "prometheus-stack-grafana"