apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-umami-secrets
  namespace: umami
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cnpg-umami-vault-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data: 
    - secretKey: username
      remoteRef:
        key: umami
        property: POSTGRES_USER
    - secretKey: password 
      remoteRef:
        key: umami
        property: POSTGRES_PASSWORD
