extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: SecretStore
    metadata:
      name: vault-backend
      namespace: argocd
    spec:
      provider:
        vault:
          server: "http://hashicorp-vault.hashicorp-vault.svc.cluster.local:8200"
          path: "secret"
          version: "v2"
          auth:
            kubernetes:
              mountPath: "kubernetes"
              role: "argocd-role"
              serviceAccountRef:
                name: "argocd-dex-server"
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret 
    metadata:
      name: argocd-secret
      namespace: argocd
    spec:
      refreshInterval: "1h"
      secretStoreRef:
        name: vault-backend
        kind: SecretStore
      target:
        name: argocd-oidc-secret
        creationPolicy: Owner
        template:
          metadata:
            labels:
              app.kubernetes.io/part-of: argocd
      data:
        - secretKey: client-secret
          remoteRef:
            key: secret/data/argocd 
            property: client_secret
        - secretKey: client-id
          remoteRef:
            key: secret/data/argocd 
            property: client_id
        - secretKey: root-ca
          remoteRef:
            key: secret/data/argocd 
            property: root_ca


server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack


configs:
  cm:
    url: https://argo.lisa
    oidc.config: |
      name: Authentik
      issuer: https://authentik.lisa/application/o/argo-cd/
      clientID: $argocd-oidc-secret:client-id
      clientSecret: $argocd-oidc-secret:client-secret

      rootCA: $argocd-oidc-secret:root-ca

  rbac:
    policy.csv: |
      g, sso_argocd_admins, role:admin 
