grafana:
  extraSecretMounts:
    - name: grafana-secret
      mountPath: /etc/secrets/grafana
      secretName: grafana-oidc-secret
      readOnly: true

  grafana.ini:
    server:
      domain: grafana.lisa
      root_url: https://grafana.lisa

    auth.generic_oauth:
        enabled: true
        name: "Authentik"
        client_id: "v879wdfHV8JzLKG2XT7ydY4YgwOTlVgZVayjhVsI"
        client_secret: $__file{/etc/secrets/grafana/oidc_secret}
        scopes: "openid profile email"
        auth_url: "https://authentik.lisa/application/o/authorize/"
        token_url: "https://authentik.lisa/application/o/token/"
        api_url: "https://authentik.lisa/application/o/userinfo/"
        role_attribute_path: "contains(groups, 'sso_grafana_admins') && 'Admin' || contains(groups, 'sso_grafana_editors') && 'Editor' || 'Viewer'"
        email_attribute_path: "email"
        name_attribute_path: "name"
        login_attribute_path: "preferred_username"
        allow_sign_up: true
        skip_org_role_sync: false
        tls_client_ca: /etc/secrets/grafana/ca_root