apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.1
    - repoURL: https://github.com/ej-east/lisa-cluster
      targetRevision: HEAD
      path: manifests/cert-manager/lisa
    - repoURL: https://github.com/ej-east/lisa-cluster
      targetRevision: HEAD
      path: manifests/cert-manager/cheesedipper
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
