apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.3
      helm:
        valueFiles:
          - $values/manifests/cilium/values.yaml
    - repoURL: https://github.com/ej-east/lisa-cluster
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ej-east/lisa-cluster
      targetRevision: HEAD
      path: manifests/cilium/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResources=true
    automated:
      prune: true
      selfHeal: true
