apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lisa-blog
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/blog/
    repoURL: https://github.com/ej-east/lisa-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

