apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: wireguard
data:
  wg0.conf.template: "[Interface]\nAddress = 10.200.0.2/24\n# Inject Private Key and Traefik endpoint at runtime\n\nPostUp = iptables -t nat -A PREROUTING -i wg0 -p tcp --dport 80 -j DNAT --to-destination TRAEFIK_EP_WEB && iptables -t nat -A PREROUTING -i wg0 -p tcp --dport 443 -j DNAT --to-destination TRAEFIK_EP_WEBSECURE && iptables -t nat -A POSTROUTING -s 10.200.0.0/24 ! -o wg0 -j MASQUERADE\n\nPostDown = iptables -t nat -S PREROUTING | grep '\\-i wg0' | sed 's/^-A/-D/' | while read rule; do iptables -t nat $rule; done; iptables -t nat -D POSTROUTING -s 10.200.0.0/24 ! -o wg0 -j MASQUERADE 2>/dev/null\n\n[Peer]\n# OCI Machine \nPublicKey = UyFXC1x34YifwYi0KL8MP6F2DBvdWWys57m9LQge6mg=\nEndpoint = 129.158.253.226:51820\nAllowedIPs = 10.200.0.1/32\nPersistentKeepalive = 25\n"
