apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wireguard-secret
  namespace: wireguard 
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: wireguard-vault-secrets
    creationPolicy: Owner
  data:
    - secretKey: wireguard_client
      remoteRef:
        key: wireguard
        property: wireguard_client
 
