apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghcr.io/ej-east/lisa-blog:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              cpu: 20m
              memory: 50Mi
