apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-db-secrets
  namespace: memo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: memos-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: memos
        property: postgresql_username
    - secretKey: password
      remoteRef:
        key: memos
        property: postgresql_password
    - secretKey: DSN
      remoteRef:
        key: memos
        property: postgresql_url
