apiVersion: v1
kind: Service
metadata:
  labels:
    app: memos
  name: memos-svc
  namespace: memo
spec:
  ports:
    - name: "5230"
      port: 5230
      protocol: TCP
      targetPort: 5230
  selector:
    app: memos
  type: ClusterIP
